input {
  beats {
    port => 5044
  }
}

filter {
  grok {
    match => { "message" => "%{GREEDYDATA:log_line}" }
  }
}

output {
  elasticsearch {
    hosts => ["localhost:9200"]
    index => "pxe-logs-%{+YYYY.MM.dd}"
  }
}
